name: Auto-Update Streamlit App

on:
  schedule:
    - cron: "0 0 * * *"  # Ejecuta el workflow todos los días a la medianoche UTC
  workflow_dispatch:  # Permite ejecutarlo manualmente si lo necesitas

jobs:
  update-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Dummy File
        run: |
          echo "Last update: $(date)" > last_update.txt
      
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add last_update.txt
          git commit -m "Automated update - $(date)" || echo "No changes to commit"
          git push