name: Update Streamlit App Weekly

on:
  schedule:
    - cron: '0 0 * * 3'  
  workflow_dispatch: 

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Make an empty commit to trigger Streamlit Cloud update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "chore: trigger Streamlit Cloud update [skip ci]"
          git push
